# Generated by Django 3.2.4 on 2021-09-15 23:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('categoria', models.CharField(max_length=60)),
                ('stock', models.IntegerField(default=0)),
                ('precio', models.FloatField()),
                ('disponible', models.BooleanField(verbose_name='Disponibilidad')),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
                ('fecha_alta', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de alta')),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cp', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'localidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('num_doc', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='N de documento ')),
                ('apellido', models.CharField(max_length=70)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre/s')),
                ('fecha_nac', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de  nacimiento')),
                ('telefono', models.IntegerField(default=10000)),
                ('localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='persona_localidad', to='tienda.localidad')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='N de movimiento')),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimiento_cliente', to='tienda.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_articulo', to='tienda.articulo')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_movimiento', to='tienda.movimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('legajo', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleado_cargo', to='tienda.cargo')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleado_persona', to='tienda.persona')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cliente_persona', to='tienda.persona'),
        ),
    ]
